In [6]:
import matplotlib.pyplot as plt
import numpy as np

In [7]:
x=[180,170,170,175,181,175,177,185,179,160]
y=[95,70,60,71,60,63,83,80,75,50]

In [8]:
#x1,x1,len(x1),len(x2)

In [12]:
X = np.stack((x, y), axis=0)
X

array([[180, 170, 170, 175, 181, 175, 177, 185, 179, 160],
       [ 95,  70,  60,  71,  60,  63,  83,  80,  75,  50]])

In [14]:
sigma_1=np.cov(X)  #(x-mu0)*(y-mu1)
sigma_1

array([[ 50.62222222,  62.17777778],
       [ 62.17777778, 173.78888889]])

In [20]:
def generate_data():
    x=[180,170,170,175,181,175,177,185,179,160]
    y=[95,70,60,71,60,63,83,80,75,50]
    X = np.stack((x, y), axis=0)
    return X

def get_cov_matris(x):
    sigma_1=np.cov(X)  
    return sigma_1

In [21]:
data_1=generate_data()
get_cov_matris(data_1)

array([[ 50.62222222,  62.17777778],
       [ 62.17777778, 173.78888889]])

In [22]:
def multivariate_normal(x, d, mean, covariance):
    """pdf of the multivariate normal distribution."""
    x_m = x - mean
    return (1. / (np.sqrt((2 * np.pi)**d * np.linalg.det(covariance))) * 
            np.exp(-(np.linalg.solve(covariance, x_m).T.dot(x_m)) / 2))

In [32]:
x_1=[175,72]
d_1=2
data=generate_data()
mean_1=np.array([np.mean(data[0,:]),np.mean(data[1,:])])
cov_1=get_cov_matris(data)

In [33]:
multivariate_normal(x_1, d_1, mean_1, cov_1)

0.0022378635770797946

In [36]:
for i in range(20):
    v=164+i
    x_1=[160+i,72]
    s=multivariate_normal(x_1, d_1, mean_1, cov_1)
    print(v,"    ",s)

164      2.9878294438190718e-05
165      5.0986407887431516e-05
166      8.39939980883647e-05
167      0.00013357873209981304
168      0.00020507919528291489
169      0.0003039492787440659
170      0.0004348864281722439
171      0.0006006836578196165
172      0.0008009603242001586
173      0.0010310302691306022
174      0.0012812298616125641
175      0.0015370143198326688
176      0.0017800163850132437
177      0.0019900560620527813
178      0.0021478396090483026
179      0.0022378635770797946
180      0.00225092276497228
181      0.0021856610047343945
182      0.002048803178253749
183      0.0018540135303834729
